dbt_airflow_dag_test:
  outputs:
    dev:
      account: YTA10127-TRIGGO_PARTNER
      database: AIRFLOW_DB
      password: dPmaH8k2HzM1*!
      role: AIRFLOW_ADMIN_RL
      schema: AIRFLOW_DBT
      threads: 1
      type: snowflake
      user: GABRIELTERCEIRO
      warehouse: AIRFLOW_WH
  target: dev
